zppr_columns = [
    "Estado",
    "Número de Orden",
    "Unnamed: 2",
    "Estado.1",
    "MES Trans",
    "Centro",
    "Planta de entrega",
    "Emplazamiento",
    "Fecha de Orden",
    "Modelo",
    "Nombre de Componente",
    "Denom.gpo.artíc.ext.",
    "Ranking",
    "Material",
    "A/BAG",
    "Alternativa LMat",
    "Planificación de transporte",
    "Clase de orden",
    "Unidad de Pedido",
    "Primero material(Sí/No)",
    "Info de cable añadido",
    "Cantidad de Pedido",
    "Denominación",
    "Lugar de montaje",
    "Denominación.1",
    "Centro de subtrabajo",
    "Denominación.2",
    "Lugar de Elaboración",
    "Turno",
    "Apoyo de sub",
    "Apoyo de Elaboración",
    "Planta de Montaje",
    "Planta de SUB",
    "Planta de Elaboración",
    "Fecha prevista de finalizar el Montaje",
    "Fecha Prevista de Finalización de SUB",
    "Fecha prevista de finalizar la elaboraci",
    "Fecha de Finalización de Montaje",
    "Fecha de Finalización de SUB",
    "Fecha de trasladar el producto elaborado",
    "Fecha de finalizar la elaboración",
    "Cantidad de resultado ensamblado",
    "Cantidad de resultado de sub",
    "Cantidad de trasladar el prod elaborado",
    "Cantidad de resultado elaborado",
    "Orden de plan de montaje",
    "Orden planeado de SUB",
    "Orden de plan de elaboración",
    "Procedimiento de trabajo de repaso",
    "Tipo de trabajo de repaso",
    "Ordende Trabajo de Repaso",
    "Revisión de retrabajo",
    "Material de Trabajo de Repaso",
    "Unnamed: 53",
    "Cantidad de Pedido.1",
    "Circuitos",
    "Número total de circuitos",
    "USO",
    "CIR",
    "secuencia",
    "Indicar la eliminación",
    "Creado el",
    "Hora",
    "Creado por",
    "Modificado el",
    "Hora modificación",
    "Modificadopor",
    "Texto de mensaje",
]
